### ISSUE TITLE
Этого файла быть не должно, все исходники хранятся в каталоге src (что тесты, что приложение)

### ISSUE THREAD

**Issue by coursar** [powerlord1990/HW3.1-autotest#9]
https://github.com/powerlord1990/HW3.1-autotest/blob/a53aaabd089f21ebdd767c749a97f709dd77e640/test/java/ru/itpark/TaxiServiceTest.java#L1-L29

**Comment by powerlord1990** [comment]
ее можно просто с гитхаба удалить?

**Comment by coursar** [comment]
Конечно, так же обычно, только указываете каталог test вместо .idea

**Comment by powerlord1990** [comment]
удалил и вопрос закрыл
